services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bermuda\BssMeteoWidget\:
    resource: '../Classes/*'

  Bermuda\BssMeteoWidget\Command\SetupCommand:
    tags:
      - name: console.command
        command: 'bss-meteo:setup'
        description: 'Prepare MeteoSwiss directory structure for BSS Meteo Widget'

  Bermuda\BssMeteoWidget\Task\WeatherSchedulerTask:
    tags:
      - name: scheduler.task
